apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test
  name: tt
spec:
  replicas: 10
  selector:
    matchLabels:
      app: tt
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: tt
    spec:
      containers:
        - image: httpd
          name: httpd

status: {}
